### ISSUE TITLE
Ability to add referrer tags

### ISSUE THREAD

**Issue by 2br-2b** [pfefferle/wordpress-open-search-document#3]
Hi,

I just found this extension, and it is exactly what I needed! It works fantastically, and I wish more people used it!

It would be really helpful if I could add a referrer tag to the end of any Opensearch search (for example, https://codegito.xyz/?s=Email&mtm_campaign=opensearch)

**Comment by pfefferle** [comment]
Would a filter to extend the URL with query params be enough?

**Comment by 2br-2b** [comment]
I think so, but I'm not completely sure what you mean by that.

Other note: it might be easier to change the url to it to https://codegito.xyz/?mtm_campaign=opensearch&s=Email rather than https://codegito.xyz/?s=Email&mtm_campaign=opensearch (flipping the order of the parameters).

**Comment by pfefferle** [comment]
See: https://github.com/pfefferle/wordpress-open-search-document#how-to-add-query-params-to-the-search-urls
