### ISSUE TITLE
Doesn't work in Chrome 101

### ISSUE THREAD

**Issue by svatoupravdu** [pfefferle/wordpress-open-search-document#4]
I installed the latest plugin version 3.0.3 to my WP installation, all set up, markup is present in sourcecode and document.osdx is accessible, but Chrome v101 (Win) still doesn't offer Tab-to-search. Also tested on Notiz.blog and the issue with Chrome is present as well.
Works well with Microsoft Edge v101.

**Comment by pfefferle** [comment]
Google added a setting. You have to "activate" your website now. Have a look at: `chrome://settings/searchEngines` and search for your website.

**Comment by svatoupravdu** [comment]
Well, many thanks for pointing me to the right place. I do remember times when Chrome accepted all OpenSearch-ready websites and automatically allowed Tab-to-search functions. Apparently those times are gone and no one will manually add or "activate" my blog in their `chrome://settings/searchEngines` although it's OpenSearch capable thanks to your plugin.
Thanks again, mark the issue as resolved.
